- name: Install Base dependencies
  hosts: localhost
  connection: local
  tags:
    - base
    - docker
    - zsh
    - neovim

  tasks:
    - name: Apt update & upgrade
      become: yes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install dependencies
      become: yes
      package:
        name:
          - git
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - tmux
          - chromium-browser
          - g++
