- name: Install Base dependencies
  hosts: localhost
  connection: local
  tags:
    - base
    - docker
    - zsh

  tasks:
    - name: Apt update & upgrade
      become: yes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install dependencies
      become: yes
      package:
        name:
          - curl
          - git
