- name: Install Docker
  hosts: localhost
  connection: local
  tags:
    - develop
    - docker

  tasks:
    - name: Install docker package
      become: yes
      package:
        name:
          - docker

    - name: Install docker-compose package
      become: yes
      package:
        name:
          - docker-compose

    - name: Create docker group
      become: yes
      shell: groupadd docker
      ignore_errors: yes

    - name: Add user to docker group
      become: yes
      shell: usermod -a -G  docker $USER
      ignore_errors: yes

