- name: Install Base dependencies
  hosts: localhost
  connection: local
  tags:
    - i3

  tasks:
    - name: Install i3
      become: yes
      package:
        name:
          - i3
          - nitrogen
