- name: Install neoVim
  hosts: localhost
  connection: local
  tags:
    - base
    - neovim

  tasks:
  - name: Add unstable ppa
    become: true
    apt_repository:
      repo: ppa:neovim-ppa/unstable
      state: present
      update_cache: yes

  - name: Install
    become: true
    apt:
      name: neovim
