- name: Personal projects
  hosts: localhost
  connection: local
  vars:
    project_path: "{{ lookup('env', 'HOME') }}/personal"
  tags:
    - personal-project

  tasks:
    - name: Ansible exists
      stat:
        path: "{{ project_path }}/ansible"
      register: ansible

    - name: Personal Project Ansible
      git:
        repo: 'git@github.com:brayangr/ansible.git'
        bare: true
        dest: "{{ project_path }}/ansible"
      when: ansible.stat.exists == False
